INSERT INTO PhoneManufacture (Name)
VALUES ('Acer'),
       ('Akai'),
       ('Alcatel Mobile'),
       ('Amazon'),
       ('Amoi'),
       ('Apple'),
       ('Archos'),
       ('Arise India'),
       ('ASBIS'),
       ('Asus'),
       ('BBK Electronics'),
       ('Bellperre'),
       ('Benefon'),
       ('BenQ'),
       ('Binatone'),
       ('BlackBerry'),
       ('BLU Products'),
       ('Brondi'),
       ('Bullitt Group'),
       ('Casio'),
       ('CECT'),
       ('Celkon'),
       ('China Electronics Corporation'),
       ('Coolpad'),
       ('Cosmic Technologies'),
       ('Cubot'),
       ('Currys plc'),
       ('Danger'),
       ('DBTel'),
       ('Dell'),
       ('Doro'),
       ('Ericsson'),
       ('Essential Products'),
       ('EvertekTunisie'),
       ('Evolveo'),
       ('Fairphone'),
       ('Firefly Mobile'),
       ('Foxconn'),
       ('Fujitsu'),
       ('GeeksPhone'),
       ('Gigabyte Technology'),
       ('Gigaset Communications'),
       ('Gionee'),
       ('Goldvish'),
       ('Google'),
       ('Gresso'),
       ('Groupe Bull'),
       ('Grundig Mobile'),
       ('GTel Zimbabwe'),
       ('Haier'),
       ('Hisense'),
       ('Hitachi'),
       ('HMD Global'),
       ('HTC'),
       ('Huawei'),
       ('IBall'),
       ('IGB Eletrônica'),
       ('Infinix Mobile'),
       ('InFocus'),
       ('InfoSonics Corporation'),
       ('Intel'),
       ('Intex Technologies'),
       ('Inventec'),
       ('IQOO'),
       ('IRiver'),
       ('Itel Mobile'),
       ('Jablotron'),
       ('Japan Radio Company'),
       ('JCB'),
       ('Jeotex'),
       ('Jolla'),
       ('Just5'),
       ('Karbonn Mobiles'),
       ('Kazam'),
       ('Kejian Group'),
       ('Kyocera'),
       ('Kyocera Communications'),
       ('Kyoto Electronics'),
       ('Lanix'),
       ('Lava International'),
       ('Lenovo'),
       ('LG'),
       ('LG Cyon'),
       ('LG Electronics'),
       ('LYF'),
       ('M4Tel'),
       ('Marshall Amplification'),
       ('Medion'),
       ('Meitu'),
       ('Meizu'),
       ('Micromax Informatics'),
       ('Microsoft'),
       ('Microsoft Mobile'),
       ('Mio Technology'),
       ('Mirgor'),
       ('Mitsubishi Electric'),
       ('MLS Innovation'),
       ('Mobicel'),
       ('MobiWire'),
       ('Motorola Mobility'),
       ('Multilaser'),
       ('NEC'),
       ('NEC Mobile Communications'),
       ('New Generation Mobile'),
       ('Nexian'),
       ('Ninetology'),
       ('Ningbo Bird'),
       ('Nubia Technology'),
       ('Obi Worldphone'),
       ('Olivetti'),
       ('Onda Mobile Communication'),
       ('OnePlus'),
       ('Onida Electronics'),
       ('Oppo'),
       ('Panasonic'),
       ('Pantech'),
       ('Pantech Wireless'),
       ('Peiker Acustic'),
       ('Philips'),
       ('Pine64'),
       ('Poco'),
       ('Positivo Tecnologia'),
       ('Purism');